script_template: "custom-inno-setup-script.iss"
app_id: com.splasher.launcher
publisher_name: Splasher
publisher_url: https://splasher.example.com
display_name: Splasher
install_dir_name: Splasher
create_desktop_icon: true
locales:
  - en